SRCS=\
	main.cpp\
	utils.cpp\
	extCheck.cpp

MODELS=\
	models/srcs/BaseBlock.cpp\
	models/srcs/CommonExceptions.cpp\
	models/srcs/Server.cpp\
	models/srcs/Container.cpp\
	models/srcs/LocationConfig.cpp\
	models/srcs/parser.cpp\
	models/srcs/lexer.cpp\
	models/srcs/readFile.cpp\
	models/srcs/SocketManager.cpp\
	models/srcs/HttpUtils.cpp\
	models/srcs/HttpResponse.cpp\
	models/srcs/HttpRequest.cpp\
	models/srcs/HttpParser.cpp\
	models/srcs/requestContext.cpp\
	models/srcs/ResourceGuards.cpp\
	models/srcs/CgiHandle.cpp\

TEMPLATES=\

HEADERS=\
	models/headers/BaseBlock.hpp\
	models/headers/CommonExceptions.hpp\
	models/headers/Server.hpp\
	models/headers/Container.hpp\
	models/headers/LocationConfig.hpp\
	models/headers/parser.hpp\
	models/headers/SocketManager.hpp\
	models/headers/HttpUtils.hpp\
	models/headers/HttpResponse.hpp\
	models/headers/HttpRequest.hpp\
	models/headers/HttpParser.hpp\
	models/headers/requestContext.hpp\
	models/headers/ResourceGuards.hpp\
	models/headers/CgiHandle.hpp\
