#!/usr/bin/env python3
"""
Example CGI script - Hello World
Access at: http://localhost:8080/cgi-bin/hello.py
"""

import os
import datetime

print("Content-Type: text/html")
print()  # Empty line separates headers from body

# Get some environment info
server_name = os.environ.get('SERVER_NAME', 'localhost')
server_port = os.environ.get('SERVER_PORT', '8080')
request_method = os.environ.get('REQUEST_METHOD', 'GET')
remote_addr = os.environ.get('REMOTE_ADDR', 'unknown')
current_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

print(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CGI Demo | Swiss Journey</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 2rem;
        }}
        .card {{
            background: white;
            border-radius: 20px;
            box-shadow: 0 25px 50px rgba(0, 0, 0, 0.3);
            padding: 3rem;
            max-width: 600px;
            width: 100%;
            text-align: center;
        }}
        .icon {{
            font-size: 4rem;
            margin-bottom: 1rem;
        }}
        h1 {{
            color: #2C5F41;
            font-size: 2.5rem;
            margin-bottom: 1rem;
        }}
        .subtitle {{
            color: #666;
            font-size: 1.1rem;
            margin-bottom: 2rem;
        }}
        .info-grid {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 1rem;
            margin-bottom: 2rem;
            text-align: left;
        }}
        .info-item {{
            background: #f8f9fa;
            padding: 1rem;
            border-radius: 10px;
            border-left: 4px solid #7BA05B;
        }}
        .info-label {{
            color: #888;
            font-size: 0.8rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }}
        .info-value {{
            color: #333;
            font-weight: 600;
            margin-top: 0.25rem;
        }}
        .success-badge {{
            display: inline-block;
            background: #d4edda;
            color: #155724;
            padding: 0.5rem 1.5rem;
            border-radius: 50px;
            font-weight: 600;
            margin-bottom: 2rem;
        }}
        .btn {{
            display: inline-block;
            background: #2C5F41;
            color: white;
            padding: 1rem 2rem;
            font-size: 1rem;
            font-weight: 600;
            text-decoration: none;
            border-radius: 10px;
            transition: all 0.3s;
        }}
        .btn:hover {{
            background: #7BA05B;
            transform: translateY(-2px);
        }}
    </style>
</head>
<body>
    <div class="card">
        <div class="icon">🐍</div>
        <h1>CGI is Working!</h1>
        <p class="subtitle">This page was dynamically generated by Python</p>
        <div class="success-badge">✓ Server Running Successfully</div>
        <div class="info-grid">
            <div class="info-item">
                <div class="info-label">Server</div>
                <div class="info-value">{server_name}:{server_port}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Method</div>
                <div class="info-value">{request_method}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Your IP</div>
                <div class="info-value">{remote_addr}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Time</div>
                <div class="info-value">{current_time}</div>
            </div>
        </div>
        <a href="/pages/homepage.html" class="btn">← Back to Homepage</a>
    </div>
</body>
</html>
""")
